main/urls.py
from unicodedata import name
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('home/',views.home, name='home'),
    path('sign-up/',views.sign_up, name='sign_up'),
    path('create-post/',views.create_post, name='create_post'),
]

website/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('',include('main.urls')),
    path('',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User , on_delete=models.CASCADE)
    title =  models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title + "\n" + self.description

main/forms.py
from unicodedata import name
from attr import field
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model =  User
        fields = ["username", "first_name", "last_name", "email" ,"password1", "password2"]

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description"]

main/views.py
from django.shortcuts import render , redirect
from .forms import PostForm, RegisterForm
from django.contrib.auth.decorators import login_required , permission_required
from django.contrib.auth import login , logout , authenticate
from . models import Post

# Create your views here.
@login_required(login_url='/login')
def home(requests):
    posts = Post.objects.all()

    if requests.method == "POST":
        post_id = requests.POST.get("post-id")
        post = Post.objects.filter(id=post_id).first()
        if post and post.author == (requests.user or requests.user.has_perms("main.delete_post")):
            post.delete()
        # print(post_id)
    return render(requests, 'main/home.html', {"posts":posts})


def sign_up(requests):
    if requests.method == 'POST':
        form = RegisterForm(requests.POST)
        if form.is_valid():
            user = form.save()
            login(requests, user)
            return redirect('/home')
    else:
        form = RegisterForm()
    
    return render(requests, 'registration/sign_up.html' , {'form':form})


@login_required(login_url='/login')
def create_post(requests):
    if requests.method == "POST":
        form = PostForm(requests.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = requests.user
            post.save()
            return redirect("/home")
    else:
        form = PostForm()
    return render(requests, 'main/create_post.html', {"form":form})

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <title>{% block title %}My Site{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <div class="container-fluid">
            <div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="/home" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="/create-post" class="nav-link">Post</a>
                    </li>
                </ul>
            </div>

            <div>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <span class="navbar-text">Logged in as {{user.username}} | </span>
                    <li class="nav-item">
                        <a href="/logout" class="nav-link">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="/login" class="nav-link">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>

        </div>
    </nav>
    <div class="container-fluid">
        {% block content %} {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>

</html>

main/templates/main/create_post.html
{% extends 'main/base.html' %}
{% block title %}Login{% endblock %}

{% load crispy_forms_tags %}


{% block content %}
<center><h3>Create Post</h3></center>
<form method="post">
    {% csrf_token %} {{form|crispy}}
    <button type="submit" class="btn btn-success">POST</button>
</form>

<style>
    * {
        color: black;
    }

    div {
        display: grid;
        justify-content: center;
        /* padding: 1em; */
        /* margin-bottom: 1em; */
    }

    nav {
        margin-bottom: 2em;
    }

    #id_title {
        /* background-color: black; */
        border: 3px solid black;
        border-radius: 20px;
        padding: 1em 2em 1em 2em;
        width: 30em;
        margin-bottom: 2em;
    }
    #id_description{
        border: 3px solid black;
        border-radius: 20px;
        padding: 1em 2em 1em 2em;
        width: 50em;
        margin-bottom: 2em;
    }
</style>
{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}
{% block title %}Home{% endblock title %}


{% block content %}
{% for post in posts %}
<div class="card mt-2">
    <div class="card-header"><strong>@{{ post.author.username }}</strong></div>
    <div class="card-body d-flex flex-row justify-content-between">
        <div>
            <h5 class="card-title">{{post.title}}</h5>
            <p>{{post.description}}</p>
        </div>
        <div>
            {% if user == post.author or perms.main.delete_post %}

                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" name="post-id" value="{{post.id}}">Delete</button>
                </form>
                
            {% endif %}
        </div>
    </div>
    <div class="card-footer text-muted">
        {{post.created_at}}
    </div>
</div>
{% empty %}
<p>No Posts </p>
{% endfor %}
{% endblock %}